name: Publish Layer

on:
  workflow_dispatch:
    inputs:
      bun_version:
        description: The version of Bun (e.g. 0.4.0).
        required: true
        type: string
      architecture:
        default: x86_64
        description: The CPU architecture the runtime is for.
        options:
          - x86_64
          - arm64
        required: true
        type: choice
      aws_region:
        default: us-east-1
        description: The AWS region to publish the lambda to.
        required: true
        type: string
      os:
        default: al2
        description: The AWS lambda operating system to publish for.
        options:
          - al1
          - al2
        required: true
        type: choice

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: Publish Buntime-${{ inputs.architecture }}-${{ inputs.os }}-v${{ inputs.bun_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ inputs.aws_region }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          cd runtime
          bun install
      - run: ./scripts/build-layer.sh ${{ inputs.bun_version }} ${{ inputs.architecture }}
      - run: ./scripts/publish-layer.sh ${{ inputs.bun_version }} ${{ inputs.architecture }} ${{ inputs.os }}
