name: Publish Layer

on:
  workflow_dispatch:
    inputs:
      bun_version:
        description: The version of Bun.
        required: true
        type: string
      architecture:
        default: x86_64
        description: The CPU architecture the runtime is for.
        options:
          - x86_64
          - arm64
        required: true
        type: choice
      aws_region:
        default: us-east-1
        description: The AWS region to publish the lambda to
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: xhyrom/setup-bun@v0.1.6
        with:
          bun-version: latest
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ inputs.aws_region }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          cd runtime
          bun install
      - run: ./scripts/build-layer.sh ${{ inputs.bun_version }} ${{ inputs.architecture }}
      - run: |
          ./scripts/publish-layer.sh ${{ inputs.bun_version }} ${{ inputs.architecture }} al1
          ./scripts/publish-layer.sh ${{ inputs.bun_version }} ${{ inputs.architecture }} al2
